"""Canonical reason codes used by LaufKern validation and tracking."""

from __future__ import annotations

LK_RCH_NO_SHORTCUT = "LK-RCH-NO_SHORTCUT"
LK_RCH_NO_FOCUS_PATH = "LK-RCH-NO_FOCUS_PATH"
LK_RCH_MODE_BLOCKED = "LK-RCH-MODE_BLOCKED"
LK_RCH_POPUP_BLOCKED = "LK-RCH-POPUP_BLOCKED"
LK_RCH_TEXT_INPUT_BLOCKED = "LK-RCH-TEXT_INPUT_BLOCKED"

LK_MAN_INTENT_UNKNOWN = "LK-MAN-INTENT_UNKNOWN"
LK_MAN_ROUTE_UNKNOWN = "LK-MAN-ROUTE_UNKNOWN"
LK_MAN_EQUIVALENCE_INVALID = "LK-MAN-EQUIVALENCE_INVALID"

LK_TRK_MISSING_MANDATORY = "LK-TRK-MISSING_MANDATORY"
LK_TRK_CHECKSUM_INVALID = "LK-TRK-CHECKSUM_INVALID"
LK_TRK_SEQUENCE_GAP = "LK-TRK-SEQUENCE_GAP"
LK_TRK_PRODUCER_UNTRUSTED = "LK-TRK-PRODUCER_UNTRUSTED"

LK_ROL_FALLBACK_FORBIDDEN = "LK-ROL-FALLBACK_FORBIDDEN"
LK_ARC_IMPORT_VIOLATION = "LK-ARC-IMPORT_VIOLATION"

REASON_CODE_CATALOG = frozenset(
    {
        LK_RCH_NO_SHORTCUT,
        LK_RCH_NO_FOCUS_PATH,
        LK_RCH_MODE_BLOCKED,
        LK_RCH_POPUP_BLOCKED,
        LK_RCH_TEXT_INPUT_BLOCKED,
        LK_MAN_INTENT_UNKNOWN,
        LK_MAN_ROUTE_UNKNOWN,
        LK_MAN_EQUIVALENCE_INVALID,
        LK_TRK_MISSING_MANDATORY,
        LK_TRK_CHECKSUM_INVALID,
        LK_TRK_SEQUENCE_GAP,
        LK_TRK_PRODUCER_UNTRUSTED,
        LK_ROL_FALLBACK_FORBIDDEN,
        LK_ARC_IMPORT_VIOLATION,
    }
)


def is_known_reason_code(reason_code: str) -> bool:
    """Return whether one reason code is part of the canonical catalog."""

    return reason_code in REASON_CODE_CATALOG
